### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by karneaud** [mmckegg/atom-npm-init#1]
[Enter steps to reproduce below:]
1. created new directory
2. add directory to project folder
3. press ctrl + alt + n

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [npm-init](https://github.com/mmckegg/atom-npm-init) package, v1.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/kendallarneaud/.atom/packages/npm-init/index.js:11

TypeError: Cannot read property 'getPath' of undefined
  at atom-workspace.initEmpty (/Users/johnd/.atom/packages/npm-init/index.js:11:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -2:00.1.0 application:add-project-folder (atom-text-editor.editor.is-focused)
  2x -1:44.7.0 npm-init:empty (atom-text-editor.editor.is-focused)
     -1:10.4.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
     -0:58.8.0 npm-init:empty (atom-text-editor.editor.is-focused)
     -0:44.9.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
     -0:02.1.0 npm-init:empty (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/johnd/Documents/Git"
  }
}
```
### Installed Packages

``` coffee
# User
atomatigit, v1.5.4
browser-refresh-on-save, v0.0.4
build, v0.46.0
command-toolbar, v1.0.12
compare-files, v0.6.2
git-go, v1.0.1
git-log, v0.4.1
jshint, v1.7.0
language-diff, v0.3.1
linter, v1.5.2
linter-csslint, v1.0.5
linter-htmlhint, v0.1.1
linter-sass-lint, v0.1.4
npm-init, v1.0.1
rest-client, v0.4.0
sass-compiler, v0.4.0
sass-watch, v0.3.1

# Dev
No dev packages
```

**Comment by mmckegg** [comment]
fixed in v1.0.2

thanks for reporting!
